void test1()
{
	try
	{
		// Do some stuff here
		if (1)
		{
			throw std ::exception();
		}
		else
		{
			// Do some more stuff
		}
	}
	catch (std ::exception e)
	{
		// Handle the error Here
	}
}